services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en1c-users:latest
    #ports:
    #  - "3000:3000"
    networks:
      - monitor-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/yovi
      - JWT_SECRET=gamey_secret_26
    depends_on:
      - mongo

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:8000
        - VITE_GATEWAY_URL=http://localhost:8000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en1c-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en1c-gamey:latest
    #ports:
    #  - "4000:4000"
    networks:
      - monitor-net

  gateway:
    build: ./gateway
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_en1c-gateway:latest
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    environment:
      - JWT_SECRET=gamey_secret_26
    depends_on:
      - users
      - gamey

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo-data:
