ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****
endif::arc42help[]

=== Quality Tree

The following diagram shows the hierarchical structure of the main non-functional requirements.

image::QualityTree.svg[Quality Tree, align="center", width=800]

ifdef::arc42help[]
[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****
endif::arc42help[]

=== Quality Scenarios

[options="header",cols="1,2"]
|===
|Quality Goal|Scenario|Description|Measure
| Time Behaviour | Fast game action processing | Backend validates player's move and frontend updates the board quickly. | Move is visible to players within a second.
| Time Behaviour | Page loading | The frontend should load the application and the game lobby without excessive delay. | No longer than five seconds to load the game page.
| Ease-of-Use | First time user starts a game | A new user opens the app for the first time and wants to start a match. | First time user should be able to start a match within two minutes of opening the app.
| Ease-of-Use | Intuitive game interface | Players are automatically aware of whose turn it is and how to do their move without thinking. | User testing with new users does not show any signs of struggle with the gameplay use.
| Attractiveness | Pleasant user interface | Consistent layout and color scheme across the application. | Test users do not complain about annoyance with the application's outlook.
| Availability | Server stability | Game should be available for players as much as possible. | MTBF goal of over 99%
| Consistency | Game state tracking | Game state is stored in the backend correctly upon each move. | Final game state stored correctly in the database after each game.
| Resilience | Handling connection failures | Players should be able to restore the game after losing connection. | Game can be reconnected and continued from the same state within 10 seconds of connection recovery.
| Modularity | Separate functional units | Modules should be able to be edited in isolation as much as possible, with minimal coupling between the functional units. | Modules can be tested in isolation for their functionalities.
|===

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
endif::arc42help[]